version: 2.1

jobs:
  build:
    docker:
    
    - image: cimg/node:16.14.2-browsers
    working_directory: ~/project
     
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: "Install Chromium"
          command: |
            sudo apt-get install chromium-browser

      - run:
          name: "Install dependencies"
          command: |
            npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: "Run tests"
          command: |
           npm run test:ci


      - store_test_results:
          path: ./allure-results
