version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.2.5

jobs:
  build:
    docker:
    
    - image: cimg/node:16.14.2-browsers
    working_directory: ~/project
     
    steps:

      - checkout
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          command: |
            google-chrome --version
            chromedriver --version
          name: Check install
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: "Install dependencies"
          command: |
            npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: "Run tests"
          command: |
           npm run test:ci


      - store_test_results:
          path: ./allure-results
